//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CinemaEntities : DbContext
    {
        public CinemaEntities()
            : base("name=CinemaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cliente> Cliente { get; set; }
        public DbSet<Filme> Filme { get; set; }
        public DbSet<Funcionario> Funcionario { get; set; }
        public DbSet<Genero> Genero { get; set; }
        public DbSet<Ingressos> Ingressos { get; set; }
        public DbSet<ItensVenda> ItensVenda { get; set; }
        public DbSet<Pessoa> Pessoa { get; set; }
        public DbSet<Salas> Salas { get; set; }
        public DbSet<Sessoes> Sessoes { get; set; }
        public DbSet<TiposIngresso> TiposIngresso { get; set; }
        public DbSet<Venda> Venda { get; set; }
    }
}
